//@GeneratedCode
namespace QTMusicStore.AppLogic.Contracts.App
{
    ///
    /// Generated by the generator
    ///
    public partial interface ITracksAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
