//@GeneratedCode
namespace QTMusicStore.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class TrackEdit
    {
        ///
        /// Generated by the generator
        ///
        static TrackEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public TrackEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public IdType AlbumId { get; set; }
        ///
        /// Generated by the generator
        ///
        public IdType GenerId { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.String Title { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String? Composer { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.Int64 Millisconds { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.Int64 Bytes { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.Decimal UnitPrice { get; set; }
        ///
        /// Generated by the generator
        ///
        public QTMusicStore.WebApi.Models.App.Album? Album { get; set; }
        ///
        /// Generated by the generator
        ///
        public QTMusicStore.WebApi.Models.App.Genre? Genre { get; set; }
    }
}
