//@GeneratedCode
namespace QTMusicStore.AspMvc.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Album
    {
        ///
        /// Generated by the generator
        ///
        static Album()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Album()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public IdType ArtistId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.String Title { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public QTMusicStore.AspMvc.Models.App.Artist? Artist { get; set; }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AspMvc.Models.App.Album Create()
        {
            BeforeCreate();
            var result = new QTMusicStore.AspMvc.Models.App.Album();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AspMvc.Models.App.Album Create(object other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AspMvc.Models.App.Album();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTMusicStore.AspMvc.Models.App.Album instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTMusicStore.AspMvc.Models.App.Album instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AspMvc.Models.App.Album Create(QTMusicStore.AppLogic.Models.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AspMvc.Models.App.Album();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTMusicStore.AppLogic.Models.App.Album other);
        static partial void AfterCreate(QTMusicStore.AspMvc.Models.App.Album instance, QTMusicStore.AppLogic.Models.App.Album other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTMusicStore.AppLogic.Models.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTMusicStore.AspMvc.Models.App.Artist.Create((object)other.Artist) : null;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTMusicStore.AppLogic.Models.App.Album other, ref bool handled);
        partial void AfterCopyProperties(QTMusicStore.AppLogic.Models.App.Album other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTMusicStore.AspMvc.Models.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTMusicStore.AspMvc.Models.App.Artist.Create((object)other.Artist) : null;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTMusicStore.AspMvc.Models.App.Album other, ref bool handled);
        partial void AfterCopyProperties(QTMusicStore.AspMvc.Models.App.Album other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Album other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(ArtistId, Title, Artist, Id);
        }
    }
}
