//@GeneratedCode
namespace QTMusicStore.AppLogic.Controllers.App
{
    using TEntity = Entities.App.Artist;
    using TOutModel = Models.App.Artist;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class ArtistsController : EntitiesController<TEntity, TOutModel>, Contracts.App.IArtistsAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static ArtistsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public ArtistsController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public ArtistsController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
    }
}
