//@GeneratedCode
namespace QTMusicStore.AppLogic.Controllers.App
{
    using TEntity = Entities.App.Genre;
    using TOutModel = Models.App.Genre;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class GenresController : EntitiesController<TEntity, TOutModel>, Contracts.App.IGenresAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static GenresController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public GenresController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public GenresController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
    }
}
