//@GeneratedCode
namespace QTMusicStore.AppLogic.Models.App
{
    ///
    /// Generated by the generator
    ///
    public partial class Album
    {
        ///
        /// Generated by the generator
        ///
        static Album()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Album()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        
        new internal Entities.App.Album Source
        {
            get => (Entities.App.Album)(_source ??= new Entities.App.Album());
            set => _source = value;
        }
        
        public IdType ArtistId
        {
            get => Source.ArtistId;
            set => Source.ArtistId = value;
        }
        
        public System.String Title
        {
            get => Source.Title;
            set => Source.Title = value;
        }
        
        public QTMusicStore.AppLogic.Models.App.Artist? Artist
        {
            get => Source.Artist != null ? QTMusicStore.AppLogic.Models.App.Artist.Create(Source.Artist) : null;
            set => Source.Artist = value?.Source;
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTMusicStore.AppLogic.Models.App.Artist.Create((object)other.Artist) : null;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Album other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Album other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTMusicStore.AppLogic.Models.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTMusicStore.AppLogic.Models.App.Artist.Create((object)other.Artist) : null;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTMusicStore.AppLogic.Models.App.Album other, ref bool handled);
        partial void AfterCopyProperties(QTMusicStore.AppLogic.Models.App.Album other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Album other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(ArtistId, Title, Artist, Id);
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Album Create()
        {
            BeforeCreate();
            var result = new QTMusicStore.AppLogic.Models.App.Album();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Album Create(object other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AppLogic.Models.App.Album();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Album Create(QTMusicStore.AppLogic.Models.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AppLogic.Models.App.Album();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Album Create(Entities.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AppLogic.Models.App.Album();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Album instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Album instance, object other);
        static partial void BeforeCreate(QTMusicStore.AppLogic.Models.App.Album other);
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Album instance, QTMusicStore.AppLogic.Models.App.Album other);
        static partial void BeforeCreate(Entities.App.Album other);
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Album instance, Entities.App.Album other);
    }
}
