//@GeneratedCode
namespace QTMusicStore.AppLogic.Models.App
{
    ///
    /// Generated by the generator
    ///
    public partial class Artist
    {
        ///
        /// Generated by the generator
        ///
        static Artist()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Artist()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        
        new internal Entities.App.Artist Source
        {
            get => (Entities.App.Artist)(_source ??= new Entities.App.Artist());
            set => _source = value;
        }
        
        public System.String Name
        {
            get => Source.Name;
            set => Source.Name = value;
        }
        
        public System.Collections.Generic.List<QTMusicStore.AppLogic.Models.App.Album> Albums
        {
            get => Source.Albums.Select(e => QTMusicStore.AppLogic.Models.App.Album.Create(e)).ToList();
            set => Source.Albums = value.Select(e => e.Source).ToList();
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.App.Artist other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Name = other.Name;
                Albums = other.Albums.Select(e => QTMusicStore.AppLogic.Models.App.Album.Create((object)e)).ToList();
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Artist other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Artist other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTMusicStore.AppLogic.Models.App.Artist other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Name = other.Name;
                Albums = other.Albums.Select(e => QTMusicStore.AppLogic.Models.App.Album.Create((object)e)).ToList();
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTMusicStore.AppLogic.Models.App.Artist other, ref bool handled);
        partial void AfterCopyProperties(QTMusicStore.AppLogic.Models.App.Artist other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Artist other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(Name, Albums, Id);
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Artist Create()
        {
            BeforeCreate();
            var result = new QTMusicStore.AppLogic.Models.App.Artist();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Artist Create(object other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AppLogic.Models.App.Artist();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Artist Create(QTMusicStore.AppLogic.Models.App.Artist other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AppLogic.Models.App.Artist();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTMusicStore.AppLogic.Models.App.Artist Create(Entities.App.Artist other)
        {
            BeforeCreate(other);
            var result = new QTMusicStore.AppLogic.Models.App.Artist();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Artist instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Artist instance, object other);
        static partial void BeforeCreate(QTMusicStore.AppLogic.Models.App.Artist other);
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Artist instance, QTMusicStore.AppLogic.Models.App.Artist other);
        static partial void BeforeCreate(Entities.App.Artist other);
        static partial void AfterCreate(QTMusicStore.AppLogic.Models.App.Artist instance, Entities.App.Artist other);
    }
}
