//@GeneratedCode
namespace QTMusicStore.AppLogic.Facades.App
{
    using TOutModel = Models.App.Artist;
    ///
    /// Generated by the generator
    ///
    public sealed partial class ArtistsFacade : ControllerFacade<TOutModel>, Contracts.App.IArtistsAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static ArtistsFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public ArtistsFacade()
        : base(new QTMusicStore.AppLogic.Controllers.App.ArtistsController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public ArtistsFacade(FacadeObject facadeObject)
        : base(new QTMusicStore.AppLogic.Controllers.App.ArtistsController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
