//@GeneratedCode
namespace QTMusicStore.AppLogic.Facades.App
{
    using TOutModel = Models.App.Genre;
    ///
    /// Generated by the generator
    ///
    public sealed partial class GenresFacade : ControllerFacade<TOutModel>, Contracts.App.IGenresAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static GenresFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public GenresFacade()
        : base(new QTMusicStore.AppLogic.Controllers.App.GenresController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public GenresFacade(FacadeObject facadeObject)
        : base(new QTMusicStore.AppLogic.Controllers.App.GenresController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
