//@GeneratedCode
namespace QTMusicStore.WebApi
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
            builder.Services.AddTransient<QTMusicStore.AppLogic.Contracts.App.IAlbumsAccess<QTMusicStore.AppLogic.Models.App.Album>, QTMusicStore.AppLogic.Controllers.App.AlbumsController>();
            builder.Services.AddTransient<QTMusicStore.AppLogic.Contracts.App.IArtistsAccess<QTMusicStore.AppLogic.Models.App.Artist>, QTMusicStore.AppLogic.Controllers.App.ArtistsController>();
            builder.Services.AddTransient<QTMusicStore.AppLogic.Contracts.App.IGenresAccess<QTMusicStore.AppLogic.Models.App.Genre>, QTMusicStore.AppLogic.Controllers.App.GenresController>();
            builder.Services.AddTransient<QTMusicStore.AppLogic.Contracts.App.ITracksAccess<QTMusicStore.AppLogic.Models.App.Track>, QTMusicStore.AppLogic.Controllers.App.TracksController>();
        }
    }
}
