//@GeneratedCode
namespace QTMusicStore.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class AlbumsController : Controllers.GenericController<QTMusicStore.AppLogic.Models.App.Album, QTMusicStore.WebApi.Models.App.AlbumEdit, QTMusicStore.WebApi.Models.App.Album>
    {
        ///
        /// Generated by the generator
        ///
        static AlbumsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public AlbumsController(QTMusicStore.AppLogic.Contracts.App.IAlbumsAccess<QTMusicStore.AppLogic.Models.App.Album> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTMusicStore.WebApi.Models.App.Album ToOutModel(QTMusicStore.AppLogic.Models.App.Album accessModel)
        {
            var handled = false;
            var result = default(QTMusicStore.WebApi.Models.App.Album);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTMusicStore.WebApi.Models.App.Album.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTMusicStore.AppLogic.Models.App.Album accessModel, ref QTMusicStore.WebApi.Models.App.Album? outModel, ref bool handled);
        partial void AfterToOutModel(QTMusicStore.WebApi.Models.App.Album outModel);
    }
}
