//@GeneratedCode
namespace QTMusicStore.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class GenresController : Controllers.GenericController<QTMusicStore.AppLogic.Models.App.Genre, QTMusicStore.WebApi.Models.App.GenreEdit, QTMusicStore.WebApi.Models.App.Genre>
    {
        ///
        /// Generated by the generator
        ///
        static GenresController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public GenresController(QTMusicStore.AppLogic.Contracts.App.IGenresAccess<QTMusicStore.AppLogic.Models.App.Genre> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTMusicStore.WebApi.Models.App.Genre ToOutModel(QTMusicStore.AppLogic.Models.App.Genre accessModel)
        {
            var handled = false;
            var result = default(QTMusicStore.WebApi.Models.App.Genre);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTMusicStore.WebApi.Models.App.Genre.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTMusicStore.AppLogic.Models.App.Genre accessModel, ref QTMusicStore.WebApi.Models.App.Genre? outModel, ref bool handled);
        partial void AfterToOutModel(QTMusicStore.WebApi.Models.App.Genre outModel);
    }
}
