//@GeneratedCode
namespace QTMusicStore.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class TracksController : Controllers.GenericController<QTMusicStore.AppLogic.Models.App.Track, QTMusicStore.WebApi.Models.App.TrackEdit, QTMusicStore.WebApi.Models.App.Track>
    {
        ///
        /// Generated by the generator
        ///
        static TracksController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public TracksController(QTMusicStore.AppLogic.Contracts.App.ITracksAccess<QTMusicStore.AppLogic.Models.App.Track> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTMusicStore.WebApi.Models.App.Track ToOutModel(QTMusicStore.AppLogic.Models.App.Track accessModel)
        {
            var handled = false;
            var result = default(QTMusicStore.WebApi.Models.App.Track);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTMusicStore.WebApi.Models.App.Track.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTMusicStore.AppLogic.Models.App.Track accessModel, ref QTMusicStore.WebApi.Models.App.Track? outModel, ref bool handled);
        partial void AfterToOutModel(QTMusicStore.WebApi.Models.App.Track outModel);
    }
}
